version: 2.1

jobs:
  lint:
    working_directory: ~/circleci-nodejs
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      - run: npm run lint 
  setup:
    working_directory: ~/circleci-nodejs
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      - run: npm i
  build:
    working_directory: ~/circleci-nodejs
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      - run: npm run build
  test:
    working_directory: ~/circleci-nodejs
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      - run: npm run test:cov

workflows:
  build_and_test:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - build:
          requires:
            - lint
      - test:
          requires:
            - build