version: 2.1

jobs:
  lint:
    working_directory: ~/circleci-nodejs
    docker:
      - image: "cimg/node:16.x"
    steps:
      - checkout
      - run: npm run lint 
  build:
    working_directory: ~/circleci-nodejs
    docker:
      - image: "cimg/node:16.x"
    steps:
      - checkout
      - run: npm run build
  test:
    working_directory: ~/circleci-nodejs
    docker:
      - image: "cimg/node:16.x"
    steps:
      - checkout
      - run: npm run test:cov

workflows:
  build_and_test:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - test:
          requires:
            - build