version: 2.1

orbs:
  node: circleci/node@4.1.0
  aws-ecr: circleci/aws-ecr@7.0.0

jobs:
  lint:
    working_directory: ~/circleci-nodejs
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      - run: |
          sudo npm i -g eslint@latest eslint-config-prettier@latest eslint-plugin-prettier@latest @typescript-eslint/eslint-plugin@latest @typescript-eslint/parser@latest --save-dev
          npm run lint
  setup:
    working_directory: ~/circleci-nodejs
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      - run: npm i
  build:
    working_directory: ~/circleci-nodejs
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      - run: |
          sudo npm install
          npm run build
  test:
    working_directory: ~/circleci-nodejs
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      - run: |
          sudo npm install
          npm run test

workflows:
  build_and_push_image:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
          repo: siddharthsathe
          tag: "latest,v0.1.${CIRCLE_BUILD_NUM}"
          dockerfile: /Dockerfile
          path: .
          extra-build-args: '--compress'
          requires:
            - test